config/routes.rb
Imhotep::Application.routes.draw do
  
  devise_for :users

  resources :stes_es

  get "edit/index"

  resources :users

  resources :zals

  resources :dvers

  resources :wins

  resources :parts

  resources :builds

  resources :acts

  resources :abouts

  resources :contacts

  resources :sites

  resources :edit

   match "/activities" => "site#activities"

  match "/partners" => "site#partners"

  match "/ccontact" => "site#contacts"

  match "/building" => "site#building"

  match "/windows" => "site#windows"

  match "/doors" => "site#doors"

  match "/shade" => "site#shade"

  get "site/about"

  get "site/activities"

  get "site/partners"

  get "site/contacts"

  get "site/building"

  get "site/windows"

  get "site/doors"

  get "site/shade"

  get "site/new_view"
  

  root :to => "site#about"

end

app/models/about.rb
class About < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/act.rb
class Act < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/build.rb
class Build < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/dver.rb
class Dver < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/part.rb
class Part < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/stes_e.rb
class StesE < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me, :username
end

app/models/win.rb
class Win < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/zal.rb
class Zal < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/dvers_controller.rb
class DversController < ApplicationController

  before_filter :authenticate_user!

  # GET /dvers
  # GET /dvers.xml
  def index
    @dvers = Dver.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dvers }
    end
  end

  # GET /dvers/1
  # GET /dvers/1.xml
  def show
    @dver = Dver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dver }
    end
  end

  # GET /dvers/new
  # GET /dvers/new.xml
  def new
    @dver = Dver.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dver }
    end
  end

  # GET /dvers/1/edit
  def edit
    @dver = Dver.find(params[:id])
  end

  # POST /dvers
  # POST /dvers.xml
  def create
    @dver = Dver.new(params[:dver])

    respond_to do |format|
      if @dver.save
        format.html { redirect_to dvers_path }
        format.xml  { render :xml => @dver, :status => :created, :location => @dver }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dvers/1
  # PUT /dvers/1.xml
  def update
    @dver = Dver.find(params[:id])

    respond_to do |format|
      if @dver.update_attributes(params[:dver])
        format.html { redirect_to dvers_path }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dvers/1
  # DELETE /dvers/1.xml
  def destroy
    @dver = Dver.find(params[:id])
    @dver.destroy

    respond_to do |format|
      format.html { redirect_to(dvers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/dvers_helper.rb
module DversHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wins_helper.rb
module WinsHelper
end

app/helpers/zals_helper.rb
module ZalsHelper
end

app/views/dvers/_form.html.erb
<%= form_for(@dver, :html => {:multipart =>true}) do |f| %>
  <% if @dver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dver.errors.count, "error") %> prohibited this dver from being saved:</h2>

      <ul>
      <% @dver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Фотография %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Добавить"%>
  </div>
<% end %>

app/views/dvers/edit.html.erb
<h1>Editing dver</h1>

<%= render 'form' %>

<%= link_to 'Show', @dver %> |
<%= link_to 'Back', dvers_path %>

app/views/dvers/index.html.erb
<div class="header2">
Административнвя панель
</div>

<div class="main2">



<table>

  <tr>

    <td style="text-align: left;">

      <%= render :partial => '/layouts/side.html.erb' %>

    </td>


    <td style="vertical-align: top;">



<h1>Фотогалерея "Двери"</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dvers.each do |dver| %>
  <tr>
    <td><%= image_tag(dver.image_url.to_s, :width => 100) %></td>
   
    <td style="padding-left:25px;"><%= button_to 'Удалить', dver, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h3><%= link_to 'ДОБАВИТЬ ФОТОГРАФИЮ', new_dver_path %></h3>

</td>

  </tr>

</table>

  </div>

app/views/dvers/new.html.erb
<div class="header2">
Административнвя панель
</div>

<div class="main2">

  <p> <h1>Добавление фотографии в галерею "О фирме"</h1> </p>

<%= render 'form' %>

<h3><%= link_to 'Назад к списоку фотографий', dvers_path %> </h3>


</div>

app/views/dvers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @dver.image %>
</p>


<%= link_to 'Edit', edit_dver_path(@dver) %> |
<%= link_to 'Back', dvers_path %>