config/routes.rb
Imhotep::Application.routes.draw do
  
  devise_for :users

  resources :stes_es

  get "edit/index"

  resources :users

  resources :zals

  resources :dvers

  resources :wins

  resources :parts

  resources :builds

  resources :acts

  resources :abouts

  resources :contacts

  resources :sites

  resources :edit

   match "/activities" => "site#activities"

  match "/partners" => "site#partners"

  match "/ccontact" => "site#contacts"

  match "/building" => "site#building"

  match "/windows" => "site#windows"

  match "/doors" => "site#doors"

  match "/shade" => "site#shade"

  get "site/about"

  get "site/activities"

  get "site/partners"

  get "site/contacts"

  get "site/building"

  get "site/windows"

  get "site/doors"

  get "site/shade"

  get "site/new_view"
  

  root :to => "site#about"

end

app/models/about.rb
class About < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/act.rb
class Act < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/build.rb
class Build < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/dver.rb
class Dver < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/part.rb
class Part < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/stes_e.rb
class StesE < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me, :username
end

app/models/win.rb
class Win < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/zal.rb
class Zal < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/stes_es_controller.rb
class StesEsController < ApplicationController

  before_filter :authenticate_user!

  # GET /stes_es
  # GET /stes_es.xml
  def index
    @stes_es = StesE.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stes_es }
    end
  end

  # GET /stes_es/1
  # GET /stes_es/1.xml
  def show
    @stes_e = StesE.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stes_e }
    end
  end

  # GET /stes_es/new
  # GET /stes_es/new.xml
  def new
    @stes_e = StesE.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stes_e }
    end
  end

  # GET /stes_es/1/edit
  def edit
    @stes_e = StesE.find(params[:id])
  end

  # POST /stes_es
  # POST /stes_es.xml
  def create
    @stes_e = StesE.new(params[:stes_e])

    respond_to do |format|
      if @stes_e.save
        format.html { redirect_to edit_path }
        format.xml  { render :xml => @stes_e, :status => :created, :location => @stes_e }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stes_e.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stes_es/1
  # PUT /stes_es/1.xml
  def update
    @stes_e = StesE.find(params[:id])

    respond_to do |format|
      if @stes_e.update_attributes(params[:stes_e])
        format.html { redirect_to :controller => :edit, :action => :index }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stes_e.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stes_es/1
  # DELETE /stes_es/1.xml
  def destroy
    @stes_e = StesE.find(params[:id])
    @stes_e.destroy

    respond_to do |format|
      format.html { redirect_to(stes_es_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/dvers_helper.rb
module DversHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/stes_es_helper.rb
module StesEsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wins_helper.rb
module WinsHelper
end

app/helpers/zals_helper.rb
module ZalsHelper
end

app/views/stes_es/_form.html.erb
<%= form_for(@stes_e) do |f| %>
  <% if @stes_e.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stes_e.errors.count, "error") %> prohibited this stes_e from being saved:</h2>

      <ul>
      <% @stes_e.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :Заголовок %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Текст %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить изменения"%>
  </div>
<% end %>

app/views/stes_es/edit.html.erb
<div class="main2">

  <table>

  <tr>

    <td style="text-align: left;">

      <%= render :partial => '/layouts/side.html.erb' %>

    </td>


    <td style="vertical-align: top;">


    <h1>Редактирование статей</h1>

<%= render 'form' %>

</td>

  </tr>

</table>


</div>

app/views/stes_es/index.html.erb
<h1>Listing stes_es</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stes_es.each do |stes_e| %>
  <tr>
    <td><%= stes_e.name %></td>
    <td><%= stes_e.title %></td>
    <td><%= stes_e.body %></td>
    <td><%= link_to 'Show', stes_e %></td>
    <td><%= link_to 'Edit', edit_stes_e_path(stes_e) %></td>
    <td><%= button_to 'Destroy', stes_e, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stes e', new_stes_e_path %>

app/views/stes_es/new.html.erb
<h1>New stes_e</h1>

<%= render 'form' %>

<%= link_to 'Back', stes_es_path %>

app/views/stes_es/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stes_e.name %>
</p>

<p>
  <b>Title:</b>
  <%= @stes_e.title %>
</p>

<p>
  <b>Body:</b>
  <%= @stes_e.body %>
</p>


<%= link_to 'Edit', edit_stes_e_path(@stes_e) %> |
<%= link_to 'Back', stes_es_path %>