config/routes.rb
Imhotep::Application.routes.draw do
  
  devise_for :users

  resources :stes_es

  get "edit/index"

  resources :users

  resources :zals

  resources :dvers

  resources :wins

  resources :parts

  resources :builds

  resources :acts

  resources :abouts

  resources :contacts

  resources :sites

  resources :edit

   match "/activities" => "site#activities"

  match "/partners" => "site#partners"

  match "/ccontact" => "site#contacts"

  match "/building" => "site#building"

  match "/windows" => "site#windows"

  match "/doors" => "site#doors"

  match "/shade" => "site#shade"

  get "site/about"

  get "site/activities"

  get "site/partners"

  get "site/contacts"

  get "site/building"

  get "site/windows"

  get "site/doors"

  get "site/shade"

  get "site/new_view"
  

  root :to => "site#about"

end

app/models/about.rb
class About < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/act.rb
class Act < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/build.rb
class Build < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/dver.rb
class Dver < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/part.rb
class Part < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/stes_e.rb
class StesE < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me, :username
end

app/models/win.rb
class Win < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/zal.rb
class Zal < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/site_controller.rb
# encoding: utf-8

class SiteController < ApplicationController
  def about

    if locale == :ru

    @title = "О фирме"

    @ab = Site.find_by_name("about")

    end

     if locale == :est

    @title = "Firmast"

    @ab = StesE.find_by_name("about")

    end

        @about = About.all

   

  end

  def activities

    if locale == :ru
    @title = "Виды деятельности"

    @activities = Site.find_by_name("activities")
    end

    if locale == :est

      @title = "Tegevusalad"

    @activities = StesE.find_by_name("activities")

    end


    @act = Act.all

  end

  def partners

    if locale == :ru
    @title = "Партеры"

    @partners = Site.find_by_name("partners")
    end

    if locale == :est

     @title = "Partnerid"

    @partners = StesE.find_by_name("partners")

    end

    @part = Part.all

  end

  def contacts
    if locale == :ru
    @title = "Контакты"

    @cont = Contact.find_by_title("contacts")
    end

    if locale == :est
    @title = "Kontaktid"

    @cont = Contact.find_by_title("contacts")

    end
   
  end

  def building

    if locale == :ru
    @title = "Общестроительные работы"

    @building = Site.find_by_name("building")
    end

    if locale == :est

      @title = "Üldehitustööd"

    @building = StesE.find_by_name("building")
    end

    @build=Build.all
  end

  def windows

    if locale == :ru
    @title = "Окна"

    @windows = Site.find_by_name("windows")
    end

    if locale == :est
      @title = "Aknad"

    @windows = StesE.find_by_name("windows")

    end

    @wins=Win.all
  end

  def doors

    if locale == :ru
    @title = "Двери"

    @doors = Site.find_by_name("doors")
    end

    if locale == :est

      @title = "Uksed"

    @doors = StesE.find_by_name("doors")

    end

    @doo = Dver.all
  end

  def shade

    if locale == :ru
    @title = "Жалюзи"

    @shade = Site.find_by_name("shade")
    end

    if locale == :est

      @title = "Kardinad"

    @shade = StesE.find_by_name("shade")

    end

    @zal = Zal.all
  end



end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  before_filter :authenticate_user!

  # GET /sites
  # GET /sites.xml
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to edit_path }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to :controller => :edit, :action => :index }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end

  
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/dvers_helper.rb
module DversHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/stes_es_helper.rb
module StesEsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wins_helper.rb
module WinsHelper
end

app/helpers/zals_helper.rb
module ZalsHelper
end

app/views/site/about.html.erb
# encoding: utf-8

<div class="header2">
<%=  @ab.title %>

</div>

<div class="main2">




  <div class="content">



 <%= raw textilize( @ab.body ) %>

</div>



  <div class="photo">

   

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({
 
  });

  $("#otherGallery").click(function(){
        
  	images = [ <% @about.each do |about| %> '<%= (about.image_url.to_s) %>',  <%end%>];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>


     

  <a id="otherGallery"  href="#"><img src="/images/firmast.jpg" alt=""width="250px"/></a>




 
  </div>



</div>

app/views/site/activities.html.erb
<div class="header2">
<%=  @activities.title %>

</div>

<div class="main2">

  <table>

    <tr>

      <td class="content">
        <%= raw textilize( @activities.body ) %>
      </td>

      <td style="vertical-align: top;">

        <a id="otherGallery"  href="#"><img src="/images/activities.jpg" alt=""width="260px"/></a>

      </td>


    </tr>


  </table>
 

  <div>


  </div>


</div>

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({

  });

  $("#otherGallery").click(function(){

  	images = [ <% @act.each do |act| %> '<%= (act.image_url.to_s) %>',  <%end%> ];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>

app/views/site/building.html.erb
<div class="header2">
  <%=  @building.title %>

</div>
<div class="main2">

  <table>

    <tr>

      <td class="content">
        <%= raw textilize( @building.body ) %>
      </td>

      <td style="vertical-align: top;">

        <a id="otherGallery"  href="#"><img src="/images/build.png" alt=""width="260px"/></a>

      </td>


    </tr>


  </table>


  <div>


  </div>


</div>

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({

  });

  $("#otherGallery").click(function(){

  	images = [ <% @build.each do |act| %> '<%= (act.image_url.to_s) %>',  <%end%> ];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>

app/views/site/contacts.html.erb
<div class="header2">
  <%=  t(@cont.name) %>

</div>
<div class="main">

<div class="content_p">
  <h4> <%=  @cont.firmaname %> </h4>

 <h5> <%=  @cont.adress %> </h5>

 <h5>Tööaeg: <%=  @cont.time %> </h5>

 <h5> Tel.   <%=  @cont.phone %> </h5>

 <h5> GSM: <%=  @cont.fax %> </h5>

 <h5>e-mail:   <%=  @cont.email %> </h5>

</div>

<div>

  <iframe width="600" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.ee/maps?f=q&amp;source=s_q&amp;hl=ru&amp;geocode=&amp;q=P%C3%A4hklim%C3%A4e+2A,+Narva&amp;aq=0&amp;oq=p%C3%A4hklim%C3%A4e+2a&amp;sll=58.6,25&amp;sspn=3.028106,9.876709&amp;ie=UTF8&amp;hq=&amp;hnear=P%C3%A4hklim%C3%A4e+2A,+20607+Narva,+Ida-Virumaa&amp;t=m&amp;ll=59.386993,28.173065&amp;spn=0.015298,0.051498&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.ee/maps?f=q&amp;source=embed&amp;hl=ru&amp;geocode=&amp;q=P%C3%A4hklim%C3%A4e+2A,+Narva&amp;aq=0&amp;oq=p%C3%A4hklim%C3%A4e+2a&amp;sll=58.6,25&amp;sspn=3.028106,9.876709&amp;ie=UTF8&amp;hq=&amp;hnear=P%C3%A4hklim%C3%A4e+2A,+20607+Narva,+Ida-Virumaa&amp;t=m&amp;ll=59.386993,28.173065&amp;spn=0.015298,0.051498&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">Просмотреть увеличенную карту</a></small>
  
</div>
</div>

app/views/site/doors.html.erb
<div class="header2">
  <%=  @doors.title %>

</div>


<div class="main2">

  <table>

    <tr>

      <td class="content">
        <%= raw textilize( @doors.body ) %>
      </td>

      <td style="vertical-align: top;">

        <a id="otherGallery"  href="#"><img src="/images/door.jpg" alt=""width="260px"/></a>

      </td>


    </tr>


  </table>


  <div>


  </div>


</div>

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({

  });

  $("#otherGallery").click(function(){

  	images = [ <% @doo.each do |act| %> '<%= (act.image_url.to_s) %>',  <%end%> ];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>

app/views/site/partners.html.erb
<div class="header2">
  <%=  @partners.title %>

</div>
<div class="main2">

  <table>

    <tr>

      <td class="content_p">

        <h2>
          <%= t("Наши партнеры") %>
        </h2>

        <h3>
          <%= raw textilize( @partners.body ) %>
        </h3>
      </td>

      <td style="vertical-align: top;">

        

           


    <a id="otherGallery"  href="#"><img src="/images/imhotepkomp.png" alt=""/></a>


          

    

      </td>


    </tr>


  </table>


  <div>


  </div>


</div>

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({

  });

  $("#otherGallery").click(function(){

  	images = [ <% @part.each do |act| %> '<%= (act.image_url.to_s) %>',  <%end%> ];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>

app/views/site/shade.html.erb
<div class="header2">
  <%=  @shade.title %>

</div>


<div class="main2">

  <table>

    <tr>

      <td class="content">
        <%= raw textilize( @shade.body ) %>
      </td>

      <td style="vertical-align: top;">

        <a id="otherGallery"  href="#"><img src="/images/zal.jpg" alt=""width="260px"/></a>

      </td>


    </tr>


  </table>


  <div>


  </div>


</div>

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({

  });

  $("#otherGallery").click(function(){

  	images = [ <% @zal.each do |act| %> '<%= (act.image_url.to_s) %>',  <%end%> ];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>

app/views/site/windows.html.erb
<div class="header2">
  <%=  @windows.title %>

</div>


<div class="main2">

  <table>

    <tr>

      <td class="content">
        <%= raw textilize( @windows.body ) %>
      </td>

      <td style="vertical-align: top;">

        <a id="otherGallery"  href="#"><img src="/images/okna.jpg" alt=""width="260px"/></a>

      </td>


    </tr>


  </table>


  <div>


  </div>


</div>

<script type="text/javascript" charset="utf8">

$(function(){
  $("#lightBox a[rel^='prettyPhoto']").prettyPhoto({

  });

  $("#otherGallery").click(function(){

  	images = [ <% @wins.each do |act| %> '<%= (act.image_url.to_s) %>',  <%end%> ];
	titles = false;
	descriptions = false;
	$.prettyPhoto.open(images);
  });
});

</script>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :Заголовок %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Текст %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit "Сохранить изменения" %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<div class="header2">
Административнвя панель
</div>

<div class="main2">

  <table>

  <tr>

    <td style="text-align: left;">

      <%= render :partial => '/layouts/side.html.erb' %>

    </td>


    <td style="vertical-align: top;">

  
    <h1>Редактирование статей</h1>



<%= render 'form' %>

 </td>
  
  </tr>

</table>


</div>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Body</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.name %></td>
    <td><%= site.title %></td>
    <td><%= site.body %></td>
    <td><%= site.path %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @site.name %>
</p>

<p>
  <b>Title:</b>
  <%= @site.title %>
</p>

<p>
  <b>Body:</b>
  <%= @site.body %>
</p>

<p>
  <b>Path:</b>
  <%= @site.path %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>